### ISSUE TITLE
Delegation timer no longer 'fits' the field

### ISSUE THREAD

**Issue by pkactual** [Emurgo/yoroi-mobile#1062]
After the upgrade to Android 11, on two different phones, the delegation timer no longer fits the designated field. So when a 0 appears, it becomes two lines and flits back-and-forth. This appears on OnePlus devices with either OnePlus font and on a 'factory' Pixel.

**Comment by v-almonacid** [comment]
@pkactual Thanks for reporting. Added to the TODO list.

**Comment by wolverineks** [comment]
@pkactual I'm looking into this. Is it still an issue? 
If so, I have a few questions.

- Which model of pixel? Pixel 1, 2, 3, 4, 5? Is it a Pixel XL?
- Have you changed the system font size or system display size?
- Does this happen all the time, or just on certain numbers?
- Would you mind providing a [screenshot](https://support.google.com/android/answer/9075928?hl=en)?

thanks

**Comment by v-almonacid** [comment]
@wolverineks not sure if it's worth fixing this since (1) I think I might already fixed it and (2) will completely refactor this screen soon

**Comment by pkactual** [comment]
It's still happening @wolverineks and @v-almonacid but something has improved - so I'll try to get shots at the right time. Basically anytime there is more than one 0 somewhere in the time, it happens consistently. However, it's much improved in that it doesn't cause the whole remainder of the screen to jump too.

If the screen is being refactored, I think it can wait because it no longer disrupts reading the more important details below it. I'll defer to either of you if you want to close this item at this point.

**Comment by stackchain** [comment]
Closing for now
