### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Beanow** [Emurgo/yoroi-mobile#1113]
This repo seems to be lacking a license, making it essentially proprietary code.
If that's unintentional, adding a license sooner rather than later is important.

To add/change license you'll technically need explicit permission from *every contributor* to do so (as there's also no contributor agreement, meaning they keep copyright for their contribution).

_Disclaimer: comments in this thread are not legal advice._

**Comment by SebastienGllmt** [comment]
Strange, we must have missed it on this repo. Just added the MIT license which is the one we use on all our projects.
