### ISSUE TITLE
Yoroi on Android 10 go

### ISSUE THREAD

**Issue by cryptosapian** [Emurgo/yoroi-mobile#1155]
The 15 words appear on the first screen but only 14 on the 2nd , not really sure why? No scroll options

Took some photo evidence and the 2nd screen dropped to 13 xD 
![IMG_20210117_030337](https://user-images.githubusercontent.com/77559918/104829963-54ab6700-5871-11eb-94b3-799cef0fe058.jpg)
![IMG_20210117_030214](https://user-images.githubusercontent.com/77559918/104829967-64c34680-5871-11eb-8436-800d93ef7137.jpg)
![IMG_20210117_030312](https://user-images.githubusercontent.com/77559918/104829970-68ef6400-5871-11eb-9d9c-11b8c303da52.jpg)
![IMG_20210117_030235](https://user-images.githubusercontent.com/77559918/104829971-6e4cae80-5871-11eb-9fd7-25b9877ca736.jpg)

New here so dno if I did images right...

**Comment by v-almonacid** [comment]
@cryptosapian  Sorry for the late answer. As a workaround, can you please try decreasing the font size in your phone settings?

**Comment by cryptosapian** [comment]
Thank you! Worked perfectly

**Comment by wolverineks** [comment]
@cryptosapian im taking a look at this issue.
you've already indicated that you are using android 10 go. what is the make and model of the phone you are using?

**Comment by wolverineks** [comment]
@cryptosapian is this still an issue?
