### ISSUE TITLE
Unable to stake ADA with Yoroi mobile + Ledger

### ISSUE THREAD

**Issue by iimiichael** [Emurgo/yoroi-mobile#1184]
I've been trying to stake my ADA to a pool for a week now and I'm unable to do so. I've got Yoroi wallet connected to my Ledger and every time I try to delegate to a pool it just gives me a transaction error.

**Comment by v-almonacid** [comment]
Thanks for reporting. Can you please confirm that:

- [ ] You are on the latest Cardano ADA app on your Ledger device, which is 2.1.0
- [ ] You are on the latest version of Yoroi mobile, which is 3.4.0

Also, what device is it, X or S? do you get any error message?

**Comment by iimiichael** [comment]
Yes, currently running Yoroi mobile at 3.4.0, however my Cardano ADA app on my ledger is 2.0.4 but it doesnt give me any options to update (or at least I dont know how).
It is an X.
The error message that pops up is "Transaction Error - An error occurred while trying to send the transaction."

**Comment by v-almonacid** [comment]
@iimiichael to upgrade your ledger ADA app, you need to upgrade your ledger firmware first in Ledger Live. Then Ledger Live should show an update available for ADA.

But we have investigated the issue and found what's causing the error. A hot fix will be released soon.

**Comment by v-almonacid** [comment]
This should be fixed by now.
