### ISSUE TITLE
Add support for Trezor Model T on Android devices

### ISSUE THREAD

**Issue by mark-stopka** [Emurgo/yoroi-mobile#1199]
USB-C enabled mobile phones with [Android can support Trezor Model T](https://wiki.trezor.io/User_manual:Using_Trezor_with_Android), it would be great it Android version of Yoroi would have support for Trezor just like it has for Ledger.

**Comment by SebastienGllmt** [comment]
This would be a good Catalyst proposal if somebody wants to build this functionality

**Comment by mark-stopka** [comment]
> This would be a good Catalyst proposal if somebody wants to build this functionality

Maybe we could add a label "Help Needed/Catalyst Idea"?

**Comment by mark-stopka** [comment]
@codybutz, do you think this is something you may be able to do with your current skill-set?

**Comment by henry12322** [comment]
I think you should write to the Yoroi wallet support team for Help. They are fast and Reliable.
https://my.forms.app/yoroiwalleti/untitled-form

**Comment by mark-stopka** [comment]
> I think you should write to the Yoroi wallet support team for Help. They are fast and Reliable. {link removed}

Beware, this is a scam...
