### ISSUE TITLE
Cardano Newbie Needs Help With Staking! Underflow?

### ISSUE THREAD

**Issue by PuzzleheadedLength95** [Emurgo/yoroi-mobile#1245]
I just made my Cardano wallet with Yoroi on my android phone and when I try to choose any pool to stake in I get this error,

Unexpected error

Requested operation failed. This is all we know: underflow

I tried googling this error and I get nothing. I also tried deleting the wallet, then restoring it. I also cleared the cache on my phone and that did not help. Anything else I can try?

**Comment by v-almonacid** [comment]
Sorry for this inconvenience, it's a bug in the app that should be fixed in the next release (version 4.0.2). It will be out soon.

As a workaround, you can use the Yoroi extension to delegate, and then you can still use the mobile app to monitor your wallet and send/receive transactions.

**Comment by PuzzleheadedLength95** [comment]
> Sorry for this inconvenience, it's a bug in the app that should be fixed in the next release (version 4.0.2). It will be out soon.
> 
> As a workaround, you can use the Yoroi extension to delegate, and then you can still use the mobile app to monitor your wallet and send/receive transactions.

Thanks for the reply and knowing that it will be fixed soon.

**Comment by v-almonacid** [comment]
@PuzzleheadedLength95 also, this is probably not your case, but I think that error typically  occurs when there are no enough funds to make a transaction (if it's the first time you delegate, you need > 3 ADA).

**Comment by PuzzleheadedLength95** [comment]
so I need to buy about 3 ADA in order to stake any? That is odd. I seen videos of people starting to stake right away. We will see.

**Comment by v-almonacid** [comment]
Yes, you need some ADA. You can't earn rewards in a Proof of Stake network if you don't have some... stake.
The protocol requires 2 ADA as a deposit (you get it back if you undelegate) and a fraction of an ADA to pay the tx fee.
