### ISSUE TITLE
Yoroi for iOS is unable to sent any amount of Native Tokens out of Nine Quintillion.

### ISSUE THREAD

**Issue by WhitemanE0** [Emurgo/yoroi-mobile#1254]
I've sucessfuly minted 9,223,372,036,854,775,807 tokens which I've called ATHOMs.
Yoroi for iOS is unable to sent any amount of ATHOMs from the Wallet containing bit more than Nine Quintillion, no matter 1 or One Quintillion. It just hangs after hitting "confirm" button.

**Comment by WhitemanE0** [comment]
Dear Sebastien, I'm totally disagree with your point. For example Daedaus Flight is able to send up to Ten Qadrillion Assets, althougth also having issue to send more.
If user can mint 9,223,372,036,854,775,807 tokens, user should be able to work with this tokens. Who are we to decide he should avoid it? There can be a usecases.
I have to add at the moment I've checked Yoroi, I've sent the sagnificant part of 9,223,372,036,854,775,807 tockens with Daedaus Flight, and in case of Yoroi statement it has to deal with near max value is not correct, it is not even close to this limit as it was less by hundred of quadrillions...
In addition I would like to add, thats checking upper/lower limits and negative values are the basics of Verification and should be a part of testing sure for sure.

**Comment by WhitemanE0** [comment]
I would append also that during this exercise I've found issues in every piece of IOHK software I've used: cardano-node, Daedalus and Yoroi, which clearly shows Verifacation across the whole software team has a way to improve.
I'm not aware of any Bug Bounty program in Cardano ecosystem, so I did this exercise Pro Bono to benefit the community.
And It's not a kind of a good manner to close the eyes on subject clearly stating software you develop has an obvious bug.

**Comment by SebastienGllmt** [comment]
I haven't "closed my eyes on the subject" which is why this issue is not closed. I'm just letting you know that unless the Cardano specification is changed, there are limitations to how tokens with near signed 64-bit values are handled and so it's best to avoid these. This is not a personal decision from the wallet perspective -- this is is a inherit limitation of the system.
