### ISSUE TITLE
BIP39: 24 words + passphrase support

### ISSUE THREAD

**Issue by FelikZ** [Emurgo/yoroi-mobile#1259]
Dear Yoroi developers,

Is there any plan to add restore option for wallets that are created using BIP39 24 words + passphrase?

This option is available through physical ledger device.

There are currently none software wallets available that allow to restore 24 words + passphrase at the moment.
So in case device is lost, you (me) will need another physical device to restore it.

**Comment by v-almonacid** [comment]
The problem I see with this is that less experienced users may end up (unnecessarily) restoring their HW wallets directly using their recovery phrase, which breaks the whole point of never letting your private keys out of your device.

**Comment by FelikZ** [comment]
@v-almonacid maybe I am not explained clear enough, but conceptually I do not propose anything drastically new.

Currently Yoroi already supports:
"Restore Wallet" -> "24-WORD WALLET" option.

So less experienced users may end up confused already.

I just want to extend this step so it adds a new option:
"Restore Wallet" -> "24-WORD WALLET + passphrase".

![2021-04-07 17 11 19](https://user-images.githubusercontent.com/1080269/113890286-4e6bbd80-97c4-11eb-81c4-34d553c1f079.jpg)

**Comment by v-almonacid** [comment]
Agree in that it's confusing already—it's indeed something we want to improve. However, key derivation when restoring a wallet through Yoroi differs from key derivation in Ledger (they use different algorithms AFAIK), so we'd need to add a specific option for ledger HW wallets.
