### ISSUE TITLE
Unable to scroll dashboard screen while loading in progress

### ISSUE THREAD

**Issue by SamAmco** [Emurgo/yoroi-mobile#1261]
From the dashboard screen sometimes it can take a while for all of the details to load. In particular it can take around 10 seconds for my stake pool delegation info to load. While this loading is happening and the loading indicator is being shown I am unable to scroll down which is a slightly irritating user experience. I would suggest that the loading indicator should be displayed per item on this page. (i.e. one loading indicator each for "epoch progress", "your summary" and "stake pool delegated") and I should still be able to scroll on this page even if the data is not ready to be displayed yet. Regardless thanks for open sourcing this project, keep up the good work!

**Comment by wolverineks** [comment]
@SamAmco im looking into this issue. im trying to reproduce this behavior.
when you say that you are unable to scroll down, is there any content that extends below the bottom of the screen?
could you [take a screenshot](https://support.google.com/android/answer/9075928?hl=en)?
does this behavior also happen when you "pull to refresh"?

**Comment by wolverineks** [comment]
@SamAmco is this still an issue?

**Comment by SamAmco** [comment]
I will try to create a demo video or something over the weekend, sorry for the delay.

**Comment by SamAmco** [comment]
Sorry for the delay here. Whilst the dashboard is loading it looks as below with a white box that seems to even clip the "Your summary" section slightly. I am unable to scroll while it is loading.

![Screenshot from 2021-05-03 16-37-37](https://user-images.githubusercontent.com/5012146/116898699-9e586b80-ac2e-11eb-8e69-9b77d556a4d5.png)

After it has loaded it looks like this: 

![Screenshot from 2021-05-03 16-38-14](https://user-images.githubusercontent.com/5012146/116898851-ce077380-ac2e-11eb-8f1e-390428460ef8.png)

Now I can scroll down to the stake pool delegated section.

I am using a Huawei P20 on Android 10. I hope this helps.

**Comment by v-almonacid** [comment]
@SamAmco thanks for the details. We'll refactor this page soon and hopefully the UX will be much better
