### ISSUE TITLE
is there a chat / forum / slack for development conversations?

### ISSUE THREAD

**Issue by wolverineks** [Emurgo/yoroi-mobile#1263]

**Comment by SebastienGllmt** [comment]
About this project in particular, or Cardano in general?
For this project in particular, we have a dedicated Yoroi Mobile channel in the Cardano Discord (but it's not strictly for development)

**Comment by wolverineks** [comment]
ive got a bunch of contribution ideas, but id rather not communicate through github issues
is there an onboarding process? CONTRIBUTING.md?
