### ISSUE TITLE
where to get started with contributing?

### ISSUE THREAD

**Issue by wolverineks** [Emurgo/yoroi-mobile#1264]
if someone wants to get started contributing where's a good place to get started?
or is this more of an internal project at this point?
is there a contibuting.md? or a publicly viewable todo list?

**Comment by v-almonacid** [comment]
You can talk to me directly in the Cardano discord and I'll gladly give you all the guidelines you need.

**Comment by RatebSeirawan** [comment]
@v-almonacid sign me up buddy, I'm new to Cardano, which discord group should I join? could you send to the exact group link

**Comment by v-almonacid** [comment]
@RatebSeirawan sure! here's the link: https://discord.gg/tSBW96WpKZ

**Comment by RatebSeirawan** [comment]
@v-almonacid Invite Invalid
