### ISSUE TITLE
Yoroi wallet not usable after containing many native assets

### ISSUE THREAD

**Issue by falassiry** [Emurgo/yoroi-mobile#1271]
Hi,

I have been unable to use my Yoroi wallet neither through mobile or browser, after I started to accumulate many native asset tokens (NFTs) in that same wallet.

The phone version typically shows a database full error and then fails to access the saved data therefore does not open the wallet at all.

The browser version fails to complete any transactions at all.

Daedalus has been able to manage the wallet afterwards but is now also starting to have trouble after reaching 700+ NFTs.

Appreciate your help. If this is a system limitation I will be forced to segregate into multiple wallets, but would like to raise this in case it is something that has been overlooked and can be sorted.

**Comment by v-almonacid** [comment]
Thanks for reporting this. After about what number of assets did you notice this issue in Yoroi?

**Comment by falassiry** [comment]
I would say 200-250 range

**Comment by ceno666** [comment]
Checking in here with the same issue, my NFT wallet contains 316 Tokens at the moment, i guess the problems began at around 200 tokens.

Yoroi on android i not usable anymore, getting the "row is full" error...on iphone i can enter the wallet but are unable to send.
Browser Version is very slow and most of the times not working anymore.

**Comment by v-almonacid** [comment]
@ceno666 could you please check how much storage Yoroi is using in your phone? 🤔

**Comment by stackchain** [comment]
Fixed in `4.9.0`
