### ISSUE TITLE
upgrade node

### ISSUE THREAD

**Issue by wolverineks** [Emurgo/yoroi-mobile#1347]
node 10 reached end of active support over a year ago, and reached end of security support last month
additionally, there are utilities that would be beneficial to this project that require >= node 12

whats required to get node on latest? 
node v16 has another year of active support, and another 2 years of security support

**Comment by v-almonacid** [comment]
Yes, we have a few minor blockers for this but we want to do it for a while.

**Comment by wolverineks** [comment]
what are the blockers? how can I help?

**Comment by v-almonacid** [comment]
Mostly our dependency on old Cardano rust bindings. New native bindings need to be written to remove the old ones.

**Comment by LeoniePhiline** [comment]
Is there already an upstream bug report for this at IOG?

**Comment by wolverineks** [comment]
@LeoniePhiline there is a pr in the works

**Comment by wolverineks** [comment]
closed by #1461
