### ISSUE TITLE
Unknown pool

### ISSUE THREAD

**Issue by nakyll** [Emurgo/yoroi-mobile#1389]
Meta seems all ok , in desktop version is ok on dedalus is ok. In Yoroi mobile version some delegators have Unknown stake pool 

Pool id: c9a397b8aa1d963030999d4edfd0f809f290f9899c73dfa1ad3a6d70

Regards

**Comment by mmahut** [comment]
Can you try again in a while? Looks like you only recently fixed your checksum, this from few hours ago:

```
[2021-06-03 09:39:53.31 UTC] Hash mismatch from poolId 'c9a397b8aa1d963030999d4edfd0f809f290f9899c73dfa1ad3a6d70' when fetching metadata from 'https://raw.githubusercontent.com/adasquirrel01/m/main/m.json'. Expected 473757885aa41028a5a68868b95d10b7cee2e982b91a04262f0090a11109709d but got 4845a4e794417e40945202cafbd2c4752c7841f3f927f5a3ca78d955c3bac7e6.
```

**Comment by nakyll** [comment]
Where u got this??? This url is not upgraded with the newer

**Comment by nakyll** [comment]
The right one are:

https://adasquirrel.com/meta/poolmeta.json

https://adasquirrel.com/meta/extended.json

shown corretly in adapools.org .....

anyway i Updated also the old repository....

**Comment by v-almonacid** [comment]
@nakyll we are poking our backend right now and hopefully this will be fixed soon. Sorry for the inconvenience

**Comment by nakyll** [comment]
> @nakyll we are poking our backend right now and hopefully this will be fixed soon. Sorry for the inconvenience

Meanwhile we lost two delegators…

**Comment by v-almonacid** [comment]
Your pool should be showing up correctly now.
