### ISSUE TITLE
Transaction ID could not be found

### ISSUE THREAD

**Issue by JJSchaart** [Emurgo/yoroi-mobile#1418]
Within a transaction, clicking on the Green Transaction ID button, the transaction could not be found (And its in German).

(Links to https://explorer.cardano.org/de/transaction.html?id= <<)

**Comment by zuzunker** [comment]
But does it display the ID on the button before you click on it?

**Comment by zuzunker** [comment]
Which version are you using? Try it again in the latest 4.2.0 please and report if that is still an issue

**Comment by JJSchaart** [comment]
> Which version are you using? Try it again in the latest 4.2.0 please and report if that is still an issue

It does show the ID on the green button, and it is the last version (Android 4.2.0 - 07c8d9a0)

**Comment by LeoniePhiline** [comment]
Same on iOS

![68D712B5-D56B-40FC-BC36-8EBCDF670B13](https://user-images.githubusercontent.com/22329650/126073081-1f2a1810-7dff-4663-92c0-a2f9b8099ee3.png)

url is https://explorer.cardano.org/de/transaction.html?id=

![5B9C4653-DA86-4AC4-9B8C-4F2CD413E831](https://user-images.githubusercontent.com/22329650/126073173-70e33618-a4c9-4ab8-8163-270789a6b612.jpeg)

![2A29CF40-A1C5-4838-BA6E-9655B68146D0](https://user-images.githubusercontent.com/22329650/126073210-b70c47ad-77fc-4944-9793-e3e6f29c3159.jpeg)

**Comment by stackchain** [comment]
This screen was updated therefore closing it for now, perhaps related to #1633
