### ISSUE TITLE
“Sign in with biometrics” asks about access to fingerprints even though my iPhone uses Face ID and has no fingerprint sensor. 

### ISSUE THREAD

**Issue by LeoniePhiline** [Emurgo/yoroi-mobile#1467]

**Comment by wolverineks** [comment]
thanks for the issue, @LeoniePhiline 

which version of iphone?
which version iOS?
which version of yoroi mobile?
could you provide steps to reproduce?

**Comment by LeoniePhiline** [comment]
iPhone 11 Pro Max
iOS 14.6 and 14.7
Yoroi mobile 4.2.0

Enable Face ID for the first time. You’ll get a dialog saying you should give access to fingerprints. Check your localization file and where that string is used. 
I recommend rephrasing or differentiating between Face ID phones and Touch ID phones.
