### ISSUE TITLE
Face ID cannot be disabled - ends in infinite loop

### ISSUE THREAD

**Issue by LeoniePhiline** [Emurgo/yoroi-mobile#1468]
https://user-images.githubusercontent.com/22329650/126073699-4ddd796c-cb37-4b2a-94c5-374c58e39438.mov

**Comment by wolverineks** [comment]
thanks for the issue, @LeoniePhiline 

which version of iphone?
which version iOS?
which version of yoroi mobile?
could you provide steps to reproduce?

**Comment by LeoniePhiline** [comment]
iPhone 11 Pro Max 
iOS 14.6 and 14.7
Yoroi mobile 4.2.0

steps as visible in the video. Enable Face ID and use it - later disable Face ID. Cannot disable because of the infinite loop seen in the video. 
the App can only be killed from the app switcher.

**Comment by andreyfarias** [comment]
Been having this same issue with my iPhone. I have reinstalled Yoroi. And now I am not able to change my PIN or uncheck the "Sign in with your biometrics" option.

iPhone 12 Mini
iOS 14.6
Yoroi Mobile 4.2.0
Commit: 25f1438d

**Comment by wolverineks** [comment]
@LeoniePhiline @andreyfarias 
you might be able to break the loop by covering the camera after the first scan
you still wont bee able to change the setting, but you wont have to restart the app

ive got a fix and im trying to get it into the next release

**Comment by zuzunker** [comment]
Should not be happening in the latest version 4.5.2
