### ISSUE TITLE
Missing top padding in status notification sidebar when everything is okay

### ISSUE THREAD

**Issue by LeoniePhiline** [Emurgo/yoroi-mobile#1473]
Padding is missing above the green icon: 

![600239B4-FA4D-475F-B96C-75275A5E2D9C](https://user-images.githubusercontent.com/22329650/126329691-a04b9e38-7461-45e5-ac8f-d519135bef76.png)

**Comment by wolverineks** [comment]
thanks for the issue, @LeoniePhiline 

which version of iphone?
which version iOS?
which version of yoroi mobile?
could you provide steps to reproduce?

**Comment by LeoniePhiline** [comment]
Hi, sorry I posted this in the wrong project. :)
It’s ledger live 😁
