### ISSUE TITLE
I can't send ada via Yoroi Mobile with ledger nano X

### ISSUE THREAD

**Issue by Voltaire3004** [Emurgo/yoroi-mobile#1543]
I cannot send an ada via Yoroi Mobile with ledger nano X. I keep getting the same error message 'Invalid asset group in the token bundle in an output - incorrect ordering of tokens' This happens when I click on confirm and Yoroi mobile normally connects to my Ledger nano X. That connection doesn't happen. I have already updated my ledger nano X via ledger manager. I have also already deleted my wallet, as well as the app and reinstalled it. All without result. How can this problem be solved so that I can send back (as before) ada from my Yoroi mobile application with my ledger nano X. Is this a known problem?

When I open my wallet via the Yoroi chrome extension version on my desktop, I can send ada. So the problem lies with Yoroi mobile version.

![IMG_8919](https://user-images.githubusercontent.com/88317468/127840114-93cc390b-47ad-49e7-b8ae-dda5142606bc.jpg)

**Comment by reqlez** [comment]
Yup same here. Ledger X is unusable with Yoroi mobile right now.

**Comment by wolverineks** [comment]
https://github.com/cardano-foundation/ledgerjs-hw-app-cardano/blob/c4abd37b1892d26adeaad61c3dbaea793771445c/src/parsing/transaction.ts#L57

**Comment by wolverineks** [comment]
https://github.com/cardano-foundation/ledgerjs-hw-app-cardano/issues/25

**Comment by zuzunker** [comment]
Hi! Latest release 4.5.2 should have all Ledger issues resolved
