### ISSUE TITLE
Error when trying to delegate on iOS

### ISSUE THREAD

**Issue by nephix** [Emurgo/yoroi-mobile#1563]
When I try to delegate ADA from the mobile app on iOS I receive an error after tapping on delegate:

![image](https://user-images.githubusercontent.com/3169205/130256872-e45ac3e1-1c32-41b2-abdc-af548f8b6703.png)

I use a Ledger Nano X, which:

- is unlocked
- has latest Cardano app
- has Cardano app open

Mobile app Version: 4.2.0
iOS Version: 14.7

**Comment by surao101** [comment]
Same issue, can't delegate to another pool, is there going to be a fix for this?

**Comment by zuzunker** [comment]
Hi @nephix and @surao101 ! Yes, sorry you are experiencing the issue, we are investigating it at the moment and hope to have the fix available in next versions.

**Comment by zuzunker** [comment]
Please check again on the latest version this should not be happening
