### ISSUE TITLE
Duplicate word in recovery phrase prevents confrimation.

### ISSUE THREAD

**Issue by chebee7i** [Emurgo/yoroi-mobile#1566]
When creating a new account, the user is required to confirm the recovery phrase by putting the words in the correct order. 

If the recovery phrase has a repeated word, then this becomes impossible since the GUI removes all instances of the repeated word when placing the first instance of that repeated word.

Afterwards, the user cannot place other instances of that repeated word and will not be able to confirm the recovery phrase.

Using android app, version 4.3.0

**Comment by zuzunker** [comment]
Fixed and will be release in version 4.5.0
