### ISSUE TITLE
Deregister Errors received from API method call while sending transaction.

### ISSUE THREAD

**Issue by Michu1982** [Emurgo/yoroi-mobile#1571]
Hi, I moved ADA to hardware wallet first time and waiting original wallet for 2-3 epochs to collect remaining rewards. Then now I'd like to deregister to move all remaining ADA to hardware wallet. System is failed which I tried both mobile and browser. it still doesnot work. How should I do? please suggest. 
Thank you very much

![240584016_10159712787149962_5110736587400929279_n](https://user-images.githubusercontent.com/89573007/130921724-d0a39c98-2308-43ef-ae2b-02302636ab8f.jpg)

**Comment by zuzunker** [comment]
Hi! Clarify please if this is still experienced or not on the latest versions of the browser or mobile version

**Comment by stackchain** [comment]
Closing for now
