### ISSUE TITLE
App crash on launch

### ISSUE THREAD

**Issue by efegure** [Emurgo/yoroi-mobile#1572]
I am getting an error and cannot access my wallet.

Error description:

Row too big to fit into CursorWindow requiredPos=0 totalRows=1

Device is android 11 Miui 12.5.2 poco f2 pro

App version : 4.3.0
![IMG-20210826-WA0001](https://user-images.githubusercontent.com/15102957/130946166-3841fd08-ac9c-413b-b695-0103a48c6d1e.jpg)

https://user-images.githubusercontent.com/15102957/131399224-5dc615e8-e8ab-435a-a028-1f3b718992da.mp4

**Comment by efegure** [comment]
Tried reinstalling and recovering my wallet 2 times but the same bug happens after killing the app and reopening it.

**Comment by manupmt** [comment]
I have the same problem, did you solve it?

**Comment by efegure** [comment]
Unfortunately no, created a ticket on emurgos website as well, they asked me if have have too many tokens(NFTs) on my wallet, my guess is that having too many crashes the app.

**Comment by manupmt** [comment]
I have the same opinion, if we install app on laptop, do you think it will work, I will try it today, let's see what happens, I will let you know....

**Comment by manupmt** [comment]
Hi, so from my laptop works fine...

**Comment by efegure** [comment]
Yes, it works from Chrome but does not work from android app.

**Comment by efegure** [comment]
Added a video

**Comment by realbluehead** [comment]
Same here! I have nfts but this should work!

**Comment by zuzunker** [comment]
Thank you for reporting and thank you for the video!

This is same as: https://github.com/Emurgo/yoroi-mobile/issues/1567

Will be addressed and fixed there.
