### ISSUE TITLE
Clicking on transaction id doesn't give  the right result.

### ISSUE THREAD

**Issue by philip-denys** [Emurgo/yoroi-mobile#1633]
Under 'transactions' when you are in a transaction.

The assumption is when you click on the transaction ID button (green) you would go to the Cardano explorer and view it

It opens up to:
https://explorer.cardano.org/de/transaction.html?id=

...Without the id

And in German language setting...

(Yes the transaction was created by a German individual, but I am not🤭)

**Comment by stackchain** [comment]
Hey @philip-denys if you click it now on the same transaction does it still show an empty id in the link? I'm wondering if is something related to when the transaction was just created because I can't simulate it here.

**Comment by philip-denys** [comment]
Yeah it still shows an empty id in the URL
so the transaction id _above_ button is showing but no direct link to the transaction when you click on it...
I can't even take a screen-recording of this :/

**Comment by stackchain** [comment]
> 
> 
> Yeah it still shows an empty id in the URL so the transaction id _above_ button is showing but no direct link to the transaction when you click on it... I can't even take a screen-recording of this :/

If you are seeing the transaction id on your button it means that your app outdated since we replace it with "Open Explorer" could you update the app and check it again?

**Comment by philip-denys** [comment]
I mentioned previously tx id 'above' the button, not on it...
