### ISSUE TITLE
Operational failure cant read saved data

### ISSUE THREAD

**Issue by Nickcald5** [Emurgo/yoroi-mobile#1636]
Can't someone help me please, I can't access my yoroi account I keep getting the above error!
I don't have seed phrase, I have app on 2 devices.
Both are throwing this message! Is there a fix!

**Comment by zuzunker** [comment]
Hi, @Nickcald5 ! Plz clarify which devices and OS you are getting the error with?

**Comment by Nickcald5** [comment]
Android mobile both devices

**Comment by Nickcald5** [comment]
![20211001_054736](https://user-images.githubusercontent.com/91738321/135625050-ff2c4d7a-1210-476b-b626-ea5968338f0c.jpg)

**Comment by zuzunker** [comment]
Thank you, @Nickcald5 ! Clarify plz which Android versions, and if possible, which phone models, that might help, as Android might being implemented differently by different vendors.

**Comment by Nickcald5** [comment]
Galaxy s21 ultra 5g
Android version 11

Other device is a galaxy tablet

**Comment by Nickcald5** [comment]
Any ideas or fixes or is my account lost along with everything in my life

**Comment by zuzunker** [comment]
> Any ideas or fixes or is my account lost along with everything in my life

@Nickcald5 , we need some time to investigate the issue and see why exactly Galaxy could fail to read the storage. Chances are it might be a software issue that we could resolve with a fix to make the storage readable again, as long as the storage itself is not corrupted.

But generally it's never advised to keep having funds in a wallet if you don't have the main secret phrase from that wallet.

**Comment by Nickcald5** [comment]
😭 ok

**Comment by zuzunker** [comment]
@Nickcald5, if you try to close the app completely and then open it again - do you see the list of your wallets and then get the error when trying to tap on one of them?

**Comment by Nickcald5** [comment]
Yes

**Comment by wolverineks** [comment]
@Nickcald5 roughly, how many transactions do these wallets have? how many tokens do they have? how many nfts do they have?

**Comment by Nickcald5** [comment]
There was about 80, I found my key words and had to open another account
The other is still locked on the app

**Comment by wolverineks** [comment]
80 what? transactions?

**Comment by Nickcald5** [comment]
Nfts

**Comment by wolverineks** [comment]
Which version of the app are you using?

**Comment by zlzlzb** [comment]
I have same issue.  
nft : 183
Yoroi 4.4.1
Galaxy s21
Android version 11

**Comment by zuzunker** [comment]
Thank you for the details, @zlzlzb! Unfortunately this is a Samsung-specific issue, yes. We are in the process of creating two potential fixes for this

**Comment by Audiemar** [comment]
Is there a fix yet as I have same issue on Samsung phone.

**Comment by Nickcald5** [comment]
Naw man they never found a fix for me I had to find my seed words otherwise
it's gone

**Comment by Audiemar** [comment]
Figures. Hope yoroi burns in hell as my seed is ruined due to a leak I had. So my only hope was a fix so I guess mine is lost.

**Comment by stackchain** [comment]
Fixed in `4.9.0`

**Comment by Audiemar** [comment]
No not fixed

**Comment by Audiemar** [comment]
I know you guys don't give a shit I lost me funds not your problem right
