### ISSUE TITLE
Recovery phrase is impossible to verify if you get duplicate words

### ISSUE THREAD

**Issue by BlakeBrown** [Emurgo/yoroi-mobile#1671]
Was helping my dad setup a Yoroi wallet and he had "oval" twice in his recovery phrase.

When he went to verify the recovery phrase, clicking "oval" removed both instances from the word list making it impossible to complete the verification step.

**Comment by zuzunker** [comment]
Fixed and will be release in version 4.5.0

**Comment by BlakeBrown** [comment]
That was so fast, thank you! 🙌
