### ISSUE TITLE
Bug: if recovery phrase contains two identical words, then there is no way to confirm the new wallet

### ISSUE THREAD

**Issue by Bidon15** [Emurgo/yoroi-mobile#1690]
Env: 
- OS: iOs 15.0.2
- App Ver: v4.4.0

Pre-Reqs: 
1. Go to App Store
2. Download latest Yoroi mobile app 

Steps to reproduce:
1. Create a new wallet 
2. Name the wallet and get the password
3. See the recovery phrase that contains 2 identical words (e.g. "extra" word)
4. Write down the recovery phrase that contains 2 identical words
5. Navigate to confirmation screen
6. See that there are 2 buttons for each of the identical words

Expected result: 
Each button for identical words are deleted separately after clicking on one of them

Actual result: 
Both buttons for identical words are simultaneously deleted after clicking on one of them, thus eliminating the possibility to finish the confirmation process

https://user-images.githubusercontent.com/1822365/137643970-f82f1d9c-9ae3-4b33-8325-205554150008.MP4

**Comment by stackchain** [comment]
Hi, @Bidon15 this bug was addressed and fixed [here](https://github.com/Emurgo/yoroi-mobile/pull/1677). Soon it will be published.
