### ISSUE TITLE
Yoroi Ledger 2.0 and Cardano 3.0 connection

### ISSUE THREAD

**Issue by juraskrlec** [Emurgo/yoroi-mobile#1696]
Hi, I am having trouble connecting my phone to yoroi, I am havibg Ledger 2.0 firmware and Cardano 3.0 installed on it, but Yoroi is searching only for 2.2.1 version. Just curious, update on the way?

**Comment by stackchain** [comment]
Hey @juraskrlec, we have some work done on it, is coming out soon.

**Comment by zuzunker** [comment]
The Ledger support got upgraded in the version 4.5.0 which is already in production now. There's currently a small additional Ledger fix awaiting to be released today in a new version 4.5.2 - once that new version is available there should be no problems working with the Ledger

**Comment by juraskrlec** [comment]
Great, thank you very much :)

**Comment by zuzunker** [comment]
Version 4.5.2 with the final Ledger fixes is being deployed at the moment
