### ISSUE TITLE
Cannot verify address on iOS with Ledger Nano X

### ISSUE THREAD

**Issue by ispiropoulos** [Emurgo/yoroi-mobile#1699]
I have 2 Ledger Xs. One has Firmware 1.3.0 the other just Updated to Firmware 2.0.0.

I am not able to do address verification with neither of those. Cardano app 2.4.1

![photo_2021-10-25 16 32 39](https://user-images.githubusercontent.com/2028642/138705511-db2d9f46-689b-4d09-9bf1-df0b003bb43b.jpeg)

Tried restarting the ledgers, remove the wallets from Yoroi and re-add. On the one with firmware 3.0.0 also followed the re-pairing guide by Ledger. Nada.

**Comment by zuzunker** [comment]
HI, @ispiropoulos, we are in the process of updating to the new version of Ledger Cardano app 3.0.0 at the moment, once this update is done - this issue most probably should not happen again, especially if you upgrade to app 3.0.0, but plz note to wait for the next release of the mobile app before doing so

**Comment by zuzunker** [comment]
This is fixed. New version containing the fix will be released today - 4.5.2 , might take couple of days to go through the stores.

**Comment by zuzunker** [comment]
Fixed in version 4.5.2 which is being deployed at the moment
