### ISSUE TITLE
We are experiencing synchronization issues

### ISSUE THREAD

**Issue by JHeisecke** [Emurgo/yoroi-mobile#1701]
For a week I haven't been able to see or withdraw my ADA on Total Rewards and Total Delegated.
I also can't see the pool I'm delegating to.

It loads and the says
> We are experiencing synchronization issues. Pull to refresh

I've seen on Reddit there are people having this issue but after sometime their connection error got resolved out of nowhere, it's been a week for me.

Device: OnePlus 6
OS: Android 10

**Comment by zuzunker** [comment]
Hi, @JHeisecke! This issue is in investigation and in work since last week. Hopefully can be resolved very soon now.

**Comment by zuzunker** [comment]
Hi, @JHeisecke ! Clarify please if the issue is still experienced at the moment and on the latest versions of the app

**Comment by JHeisecke** [comment]
it's working! thank you
