### ISSUE TITLE
UI Issue: 3 letter mnemonics (especially on iOS)

### ISSUE THREAD

**Issue by rdlrt** [Emurgo/yoroi-mobile#1705]
3 iOS users have reported an issue while restoring wallets using mnemonics on v4.4.1, for 3-letter words like `ski` - where one of the two behaviour is seen:
1. Typing `ski` shows the word correctly in pulldown for hint, but clicking on `ski` makes the cell "empty" without a way to manually type ski and skip selection. Users experienced this on iOS, but I was randomly able to replicate it *only* once on Android, but retrying since resulted in second UI behaviour below.
2. Typing 3 word letter does not show a pull down , but I am able to click on next word cell and proceed through. User reporting was able to do this, but at the end - was not able to "activate" "Restore Wallet" until hitting return key on iOS. On android you're still able to click through on next word or not have trouble clicking on Restore Wallet.

Overall the UX with 3 letter words for MnemonicsInput is a bit inconsistent

**Comment by zuzunker** [comment]
Hi, @rdlrt ! Thank you for the report with details! We have been preparing a hotfix for this, version `4.4.2` is going through the stores now, hope it might get available for public early next week.

This version contains the 3-letter issue fix specifically and makes the input handle all words properly.

In the next regular version `4.5.0` there also already added an additional improvement to the UX on that page that changes how the suggested options are displayed and how the page behaves when user goes through the list (can check it here: https://github.com/Emurgo/yoroi-mobile/pull/1703#issuecomment-954306248)

**Comment by rdlrt** [comment]
Nice, glad it's already ~sorted - looks good on the video 👍🏻 
*verified on nightly
