### ISSUE TITLE
I cannot verify a mnemonic that has duplicate word when creating a new wallet

### ISSUE THREAD

**Issue by fyang1024** [Emurgo/yoroi-mobile#1771]
Today I downloaded Yoroi wallet on iOS and created a new wallet. The mnemonic phrase has 2 `this` word. When I tried to verify that I have wrote down the mnemonic, I had to pick the 15 words in order. However there were only 14 words to pick from, because `this` only appear once in the list. I think this is probably a bug. Mnemonic can have duplicate words in it.

**Comment by stackchain** [comment]
Hey @fyang1024, it was supposed to be fixed here #1677 while restoring a wallet, got to check if the verify screen is using the same component or if it has it's own logic, thank you for bringing it up.

**Comment by highvight** [comment]
Same happened to me on Android, duplicates cannot be entered on the confirmation page.

**Comment by zuzunker** [comment]
This is now fixed in the version 4.5.0
