### ISSUE TITLE
[Android] Error when building app yoroi-mobile

### ISSUE THREAD

**Issue by lozyloop12** [Emurgo/yoroi-mobile#1976]
## Description / affected users
This bug appears to affect when running app from your source

### Steps to reproduce:
1. install node_modules (npm i)
2. run app android
Other info:
React-Native version: 0.64.2

![image](https://user-images.githubusercontent.com/16531198/166908479-aadc9874-3453-47d6-a0d6-e8267fc43295.png)
Please let me know if you need any further info,

**Comment by Nebyt** [comment]
Hi @lozyloop12 ! Did you read the instruction https://github.com/Emurgo/yoroi-mobile/blob/develop/README.md ?
Could you answer, please, what is your OS and what version of the app have you been trying to build?

**Comment by lozyloop12** [comment]
@Nebyt Hello Neby, i have followed the README, i think i am having an error problem on macOS BigSur
