### ISSUE TITLE
Android app is not working inside Samsung Knox folder

### ISSUE THREAD

**Issue by arkadym** [Emurgo/yoroi-mobile#2299]
Hello, tried install Yoroi app into my S20 , inside the Knox folder, when i run the app i cannot pass Select Language screen. When i click Next it shows agreement screen, then i click Accept and it shows fingerprint validation popup but cannot pass it. It shows error
"Something went wrong, try again later. Check your app settings."
Btw, other apps works fine with FP .

**Comment by stackchain** [comment]
🤔  hey @arkadym , can you please test this:

1. Kill the app if it's in the background
2. Disable your Biometrics/Fingerprint completely (turn it off) on the device (unfortunately Android doesn't have the same capability as iOS where you can disable it for a specific app.
3. Try to launch the app again (in this case the app will check that there is no keychain available and will ask for the pin that is stored encrypted in the device's local storage)
4. Finish the app setup (add a wallet)
5. Enable your Biometrics/Fingerprint again

My guess is since we are forcing it, maybe we will have to check while launching if something goes wrong to automatically fall back to the PIN.

Really appreciate your feedback.

**Comment by arkadym** [comment]
@stackchain in fact, i'm developer too, from my experience issue is related to Samsung Knox. My friends faced similar issue, means FP works fine when app installed outside of Knox folder. And cannot work with FP when installed inside Knox folder.
I would appreciate if you could implement FP as optional and allow set PIN.

I can try collect adb log if that will help, but will need to prepare my PC.

**Comment by arkadym** [comment]
@stackchain sorry, i cannot follow your guide, i have some other apps using FP which will force me to reauthenticate all of them because FP changed if i will turn it off completely...

**Comment by stackchain** [comment]
I've open a PR to enable continuing the app setup in this scenario, if you want to test it earlier, sign for the beta releases on Android play store. You can also download the Yoroi Nightly that we always push before deploying any new release.

**Comment by arkadym** [comment]
Thank you! Not using play store, could you point me where to find nightly builds ?

**Comment by arkadym** [comment]
Btw, i checked PR, could i propose a better solution - i've found in your codes there are 3 scenarios when error happened: cancelled, auth failure (e.g. wrong finger used) and other error (like my case), so i propose only fallback to pin when cancelled and other error, auth failure should be not fallback to pin... from security perspective. That case means someone can setup wallet on my phone, weird scenario, but still...

**Comment by stackchain** [comment]
hey @arkadym , Nightly version is also inside [Play store](https://play.google.com/store/apps/details?id=com.emurgo.nightly)

**Comment by stackchain** [comment]
> Btw, i checked PR, could i propose a better solution - i've found in your codes there are 3 scenarios when error happened: cancelled, auth failure (e.g. wrong finger used) and other error (like my case), so i propose only fallback to pin when cancelled and other error, auth failure should be not fallback to pin... from security perspective. That case means someone can setup wallet on my phone, weird scenario, but still...

The 3rd scenario, if the fingerprint fails, but everything is supposed to be fine, that's ok, the user can change the app settings later.
Android also holds the user on the sensor screen if the authentication fails, the user will have 3 attempts before failing the authentication, or the user can press cancel, which will also resume to PIN creation funnel.
