### ISSUE TITLE
Cexplorer bug causing valid pools to be blacklisted from yoroi

### ISSUE THREAD

**Issue by gusosborne** [Emurgo/yoroi-mobile#2429]
Cexplorer bug causing valid pools to be blacklisted from yoroi.

Current example is “ISYG”. They have a valid pledge, which is met (Live: 29,403 ₳ - Declared: 10,000 ₳ - cexplorer is wrongly reporting 93.01 ₳). 
ISYG is currently blacklisted from yoroi for “pledge not met” bug in cexplorer:

Please see:
https://github.com/cexplorer/cexplorer.io/issues/38

and
https://github.com/cexplorer/cexplorer.io/issues/39

This is ongoing for months now. Please put some pressure on cexplorer to fix this- or please find a new, functional provider for yoroi’s pool and delegation data. 

https://cexplorer.io/pool/pool1398yhldnhm3y7hzmf8c0h8wf4gwyqa2jd9s0vagj8srqyt7jcen

![1F3ACC1B-8CB2-465A-824E-E12B88E8EB7A](https://user-images.githubusercontent.com/25893043/230724361-417b6ec8-33f1-4f62-8232-bd6ff47088d6.jpeg)
![3A695150-DFE0-4ECF-B112-2EDA15DA3B01](https://user-images.githubusercontent.com/25893043/230724363-63a3d985-1554-4a20-8626-80a2510fe544.jpeg)

![92A755FC-4341-40D2-86D0-753282CE5836](https://user-images.githubusercontent.com/25893043/230724411-26550423-62cf-450b-b9d7-73e9da6fc168.jpeg)

https://rawcardano.app/?pool=ISYG
![2389B560-7074-418B-8E61-B29F8CA1D0CD](https://user-images.githubusercontent.com/25893043/230724487-f4ffa071-d3e3-4f3c-82fe-8e36e95dcb29.jpeg)

Thank you for your consideration.

**Comment by stackchain** [comment]
Hey @gusosborne, there is not much we can do, but I'm redirecting internally so our community manager can ping cexplorer folks about it. After we got an answer from them I'll consider it done from our side.

**Comment by stackchain** [comment]
@gusosborne, fixed, tested on all platforms.
