### ISSUE TITLE
Adding an 'Authentication' Feature.

### ISSUE THREAD

**Issue by JustLeif** [Emurgo/yoroi-mobile#3376]
I have been building some web applications, and I've been using Cardano wallet authentication with data signing, then validating the signature on my backend as described in the Cardano documentation. (https://developers.cardano.org/docs/integrate-cardano/user-wallet-authentication/)

This of course works perfectly, but I want to see a world where its friction-less for users to authenticate with their wallet. Of course this would maybe require a standardization across wallets, but I would love to implement it into Yoroi.

## The problem
<img width="493" alt="Screenshot 2024-07-08 at 4 27 58 PM" src="https://github.com/Emurgo/yoroi/assets/69766831/f32455ae-44ef-41a6-91df-d933bfafbf44">

With the current flow, a user has to sign a developer defined piece of data, this might look weird or confusing to new Cardano Wallet users, and can also look weird because us the developers define the data to sign.

## The solution

My idea would be a seperate API call called `wallet.signatureAuth()` or something, that would open up a separate UI feature that makes it clear to the user the action they are currently performing an authentication action. Then we standardize a piece of data to sign (kind of like 'Bearer: *JWT*) to perform an authentication action.

## Open to Thoughts or Reasons this is a bad idea
Of course this is just me thinking out loud and I don't really know how to get something like this implemented in the ecosystem. If this is a terrible idea I'd love to hear why! Thanks for your hard work with Yoroi and across the Cardano ecosystem.

**Comment by yushih** [comment]
@JustLeif thank you very much for raising this interesting point! The issue is being discussed internally currently.

Personally, I think a smoother upgrading approach would be to form a CIP that defines various "special" signed data forms that supporting wallets can interpret and act accordingly.

BTW, when using signed data for authentication, you might want to consider including a nonce/session id in the data.

**Comment by stackchain** [comment]
> @JustLeif thank you very much for raising this interesting point! The issue is being discussed internally currently.
> 
> Personally, I think a smoother upgrading approach would be to form a CIP that defines various "special" signed data forms that supporting wallets can interpret and act accordingly.
> 
> BTW, when using signed data for authentication, you might want to consider including a nonce/session id in the data.

Yap, @JustLeif I think a good start would be to create a draft CIP to implement the SCRAM over the Dapp connector. I'd also encourage you to move it from issue to discussion as a proposal.

**Comment by JustLeif** [comment]
> @JustLeif thank you very much for raising this interesting point! The issue is being discussed internally currently.
> 
> Personally, I think a smoother upgrading approach would be to form a CIP that defines various "special" signed data forms that supporting wallets can interpret and act accordingly.
> 
> BTW, when using signed data for authentication, you might want to consider including a nonce/session id in the data.
> 

Oh its nice to hear that others want this too. And good idea about the session id added to the data signed.

**Comment by JustLeif** [comment]
> > @JustLeif thank you very much for raising this interesting point! The issue is being discussed internally currently.
> > 
> > Personally, I think a smoother upgrading approach would be to form a CIP that defines various "special" signed data forms that supporting wallets can interpret and act accordingly.
> > 
> > BTW, when using signed data for authentication, you might want to consider including a nonce/session id in the data.
> 
> Yap, @JustLeif I think a good start would be to create a draft CIP to implement the SCRAM over the Dapp connector. I'd also encourage you to move it from issue to discussion as a proposal.

Sounds good I'll do that.
