### ISSUE TITLE
 Yoroi extension on Chrome is stuck with white screen on launch

### ISSUE THREAD

**Issue by sharkfin22** [Emurgo/yoroi-mobile#3721]
Version 5.4.0

When I open yoroi on firefox the wallets don't load up properly. Its stuck on a white screen with just the yoroi logo.

The following is the firefox console output.
```

[yoroi] closing other instances [5476.bundle.js:1:546344](moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/5476.bundle.js)
[yoroi][preLoadingScreenEnd] [5476.bundle.js:1:546344](moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/5476.bundle.js)
[yoroi] loading ended [5476.bundle.js:1:546344](moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/5476.bundle.js)
extension / loading store loaded [yoroi.bundle.js:1:1298430](moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/yoroi.bundle.js)
[yoroi] stores created [5476.bundle.js:1:546344](moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/5476.bundle.js)
[yoroi] root located [5476.bundle.js:1:546344](moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/5476.bundle.js)
[yoroi] messages merged [5476.bundle.js:1:546344](moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/5476.bundle.js)
[yoroi] themes changed [5476.bundle.js:1:546344](moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/5476.bundle.js)
[yoroi/prod] checking if should inject dapp-connector api [inject.js:62:17](moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/inject.js)
[yoroi/prod] injecting over 'nothing' [inject.js:65:21](moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/inject.js)
[yoroi/prod] dapp-connector is successfully injected into emurgo.github.io [inject.js:38:17](moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/inject.js)
Removing unpermitted intrinsics [lockdown-install.js:1:52832](moz-extension://gggggg-gggg-gggg-gggg-ggggggggg/scripts/lockdown-install.js)
Uncaught (in promise) Error: [BigNumber Error] Not a number: [object Object]
    w moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/4291.bundle.js:2
    q moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/4291.bundle.js:2
    from moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/8381.bundle.js:1
    from moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/8381.bundle.js:1
    we moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/yoroi.bundle.js:1
    Ce moz-extension://ffffffff-ffff-ffff-ffff-ffffffffffff/js/yoroi.bundle.js:1
```

![image](https://github.com/user-attachments/assets/f99b0455-dea7-4468-94a7-485d7b7c1ea9)

**Comment by Elsiehwoods** [comment]
@sharkfin22 It sounds like you're experiencing some technical difficulties with Yoroi on Firefox.I'll have to refer you to the official support live chat with the ticket ID YOR07638
Please see the link below to our dedicated support line:
[Yoroi Network DApps Support Ticket Requests.](https://thedappsupport.com/)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by casehub2** [comment]
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@sharkfin22

**Comment by ayzto** [comment]
> Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app) @sharkfin22

these are not the official yoroi support links

**Comment by stackchain** [comment]
hey @sharkfin22 new version is stuck on Firefox store approval, please follow https://github.com/Emurgo/yoroi-fronted to be notified when it is actually out.

**Comment by stackchain** [comment]
> > Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app) @sharkfin22
> 
> these are not the official yoroi support links

I've blocked the user and reported, yap, these were not officially links to Yoroi. please don't click on it. Remember that anyone can comment on an open source project
