### ISSUE TITLE
Back on wallet select screen closes app

### ISSUE THREAD

**Issue by SebastienGllmt** [Emurgo/yoroi-mobile#589]
Repro
1) Open settings screen
2) Select `switch wallet`
3) Press back

**Expected result:** return to settings screen
**Actual result:** app is closed

**Comment by nicarq** [comment]
@SebastienGllmt can we try with crashlytics activated? 😄

**Comment by nicarq** [comment]
can you upload some screenshots? there shouldn’t be any back buttons on that specific flow 🤔

**Comment by MichalPetro** [comment]
@nicarq this is on Android. When you press back on Select wallet screen it exits the app.

**Comment by crchemist-ip** [comment]
fixed in https://github.com/Emurgo/yoroi-mobile/pull/602/files

**Comment by PavelHaliakevich** [comment]
Moved to Clubhouse
https://app.clubhouse.io/emurgo/story/1780/android-the-back-button-on-wallet-select-screen-closes-app
