### ISSUE TITLE
(Android) A "Copy address" overlay is not displayed fast enough. (Receive screen)

### ISSUE THREAD

**Issue by PavelHaliakevich** [Emurgo/yoroi-mobile#605]
Currently, a user is able to click on two addresses before "Copy address" overlay will appear
Please check the video
https://emurgo.slack.com/files/UC8RZUKC0/FFGEGRN0M/20160107_033329.mp4

**Comment by PavelHaliakevich** [comment]
Moved to Clubhouse
https://app.clubhouse.io/emurgo/story/1777/android-a-copy-address-overlay-is-not-displayed-fast-enough-receive-screen

**Comment by stackchain** [comment]
This process was already changed.
