### ISSUE TITLE
(Android)"Copy address" screen transforms to overlay if you turn off the smartphone or minimize the application.

### ISSUE THREAD

**Issue by PavelHaliakevich** [Emurgo/yoroi-mobile#612]
Transaction details screen.
Please check the vid for the steps to reproduce
https://emurgo.slack.com/archives/GC9AM0E8K/p1548081509010100

**Comment by ppershing** [comment]
I suspect this problem is endemic to all modals...

**Comment by PavelHaliakevich** [comment]
Just in case - this behavior appears only on Android. On iOS "Copy address" screen is always an overlay.

**Comment by v-almonacid** [comment]
Closing as I can not reproduce. Probably fixed after react-native upgrade.
