### ISSUE TITLE
Android wallet, simple feedback

### ISSUE THREAD

**Issue by varmsaus** [Emurgo/yoroi-mobile#625]
Would it be possible to skip the login button and just be presented with the PIN screen immediately?

Also, the copy address icon next to the addresses on the receive screen. Could it be an icon by itself that copies the address instead of opening the QR code screen? 

Other than these minor things, I really like the wallet. Just some ideas to make it slightly faster to use.

**Comment by vantuz-subhuman** [comment]
Hello, @varmsaus! Thank you very much for the feedback, we are really glad to see people being happy with the app and wanting to contribute to it! So suggestions are really welcomed! =)

I have transferred the issue to the appropriate repository for the mobile wallet :)

Other than that - I think feedback looks really good, and we will definitely check out if we can make these points easier and faster! 👍

**Comment by stackchain** [comment]
Some of the suggestions were already implemented.
