### ISSUE TITLE
In certain situations it's impossible to make a transaction that leaves 0 ADA on a wallet account.

### ISSUE THREAD

**Issue by PavelHaliakevich** [Emurgo/yoroi-mobile#639]
Can be reproduced if you try to send the entire amount when the wallet balance is equal 1.000001/1.000002 ADA

Please, check out the video:
https://emurgo.slack.com/archives/GC9AM0E8K/p1550146077040500

**Comment by ppershing** [comment]
I don't have an access to the video but I would guess this is a "problem" with upstream rust implementation
