### ISSUE TITLE
(iOS) Sometimes it is possible to disable "Sign in with your biometrics" without turning off the "Easy Transaction Confirmation" feature.

### ISSUE THREAD

**Issue by PavelHaliakevich** [Emurgo/yoroi-mobile#643]
Which leads to the crash of the app if the user tries to send a transaction:
![img_0125](https://user-images.githubusercontent.com/41470567/53335059-7f057b80-390b-11e9-8c25-599e60eea00f.JPG)

Steps to reproduce this are currently unknown. I will add them later (if I can).

**Comment by PavelHaliakevich** [comment]
Link to the detailed description with steps.
https://app.clubhouse.io/emurgo/story/276/iphone-easy-transaction-confirmation-crash

**Comment by stackchain** [comment]
Fixed.
