### ISSUE TITLE
Option to hide balance

### ISSUE THREAD

**Issue by vsubhuman** [Emurgo/yoroi-mobile#651]
Many money-related mobile apps provide option to hide balance by default, and display it only when you tap on it or something like that, because user might want to open and use app in public, but then it might be awkward to open it with the balance being displayed on the screen, as people are watching.

Would be great to have option like this in Yoroi mobile too, so user can switch an option in settings and then balance will be displayed only when user taps on it, and then hidden again when app is locked or maybe in some time limit.

**Comment by stackchain** [comment]
Comming on 4.5
