### ISSUE TITLE
Blurry Launch Screen (aka splash screen)

### ISSUE THREAD

**Issue by ebeloded** [Emurgo/yoroi-mobile#657]
There is a problem with the launch screen on some iPhones: the image is stretched and blurred:

![iPhone 7](https://user-images.githubusercontent.com/5859177/55445852-74fc2a00-55e7-11e9-8e8c-879e10de101f.PNG)

We'll need to add launch screen images of all appropriate sizes and/or make sure that constraints are configured correctly.

@nicarq mentioned that the splash screen on his android devices is also blurry. Could you clarify, which device/screen size you tested it on? It's crisp on my Nexus 7.

For reference: 
[Apple Launch Screen Guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/launch-screen/)
[How to add splash screen to a react native app](https://medium.com/handlebar-labs/how-to-add-a-splash-screen-to-a-react-native-app-ios-and-android-30a3cec835ae)

**Comment by Marta-Ryzhok** [comment]
![yoroi-logo-shape-white inline](https://user-images.githubusercontent.com/45553506/55463938-5e130300-55fa-11e9-9d9e-4b460b6de6b1.png)

**Comment by Marta-Ryzhok** [comment]
attached above. 
Also if you need svg you can find Yoroi logo in all formats we use here: https://drive.google.com/drive/u/0/folders/1dfkcxoGufZZdvFpwyqHXKqqzstW_HZA4

**Comment by ebeloded** [comment]
This one is closed with #660
