### ISSUE TITLE
Authentication fallback loophole

### ISSUE THREAD

**Issue by ebeloded** [Emurgo/yoroi-mobile#659]
**Problem**

Yoroi Mobile has a security loophole when the Touch ID is enabled, which allows a person, who knows only the device PIN code, to login into the app and make a transaction without having to use the Touch ID, or knowing the wallet password.

**Explanation**

The explanation is straightforward: all you need to do is to fail the Touch ID authentication, after which the app will offer to enter the device passcode.

**Background**

TouchID is a great way to securely authenticate the user. People always use it to access password managers, pay for things, as well as for mobile banking authentication.

I checked all other financial/security apps on my phone, which use Touch ID, and Yoroi is the only app on that has this hole.

It seems that the team is aware of the problem, as the app presents the user with an explanation about the 'Easy confirmation': (bold is mine)

> This option will allow you to send ADA transactions from your wallet just by confirming with fingerprint or face recognition with **standard system fallback option**. This makes your wallet less secure. This is a compromise between UX and security!

Every other app which uses TouchID/FaceID, if it offers a fallback, it asks for the app-specific password, but not the device PIN.

**Solution**

We need to implement a proper TouchID/FaceID authentication with the app PIN fallback. I don't think the 'compromise' explanation is helpful to the user and will be unnecessary when the authentication routine is implemented correctly.

Examples with correct implementation: PayPal, Crypto.com, 1Password, any banking app.

Additionally, the whole authentication process is a bit clumsy has many issues, many of which @PavelHaliakevich has logged here. I suggest resolving all of that in one PR.

This problem needs to be confirmed on Android devices.

**Comment by SebastienGllmt** [comment]
This is by design and actually we picked the libraries in the project specifically to allow this to happen. If you decide to use biometrics, you are basically saying you are okay with with an extremely small amount of security. If somebody like a family member knows your pin, they 100% for sure can get your biometrics information with minimal effort so an extra pin won't stop them. In fact, if anybody has physical access to you, they can easily bypass the biometrics with the old [$5 wrench attack](https://xkcd.com/538/)

**Comment by SebastienGllmt** [comment]
@nicarq you can comment if you want to reopen this but since we explicitly chose to do this fallback mechanism I assume you are okay with this.

**Comment by nicarq** [comment]
@ebeloded I think as @SebastienGllmt and I think he described it well.

**Comment by ebeloded** [comment]
Hm. Just to be clear: Yoroi is the only app, which allows the system fallback, not the app fallback, unlike all other protected apps.

In other terms, Yoroi is the only app, which my 3-year-old, can accidentally hack.

All other apps (App Store, 1Password, banking apps), require to use the actual app password. I don't quite understand why we didn't go this way, especially since we do have an in-app PIN code.

If it was a decision to go this way, why did you choose to do that? It seems to undermine the app security.

**Comment by nicarq** [comment]
@SebastienGllmt after talking to @ebeloded I understood it better. I will leave it open. I think we can fix it when we get more help in mobile.
