### ISSUE TITLE
iOS crash on QR scan attempt

### ISSUE THREAD

**Issue by mcicak** [Emurgo/yoroi-mobile#855]
1. Enter wallet details and tap Send
2. Tap the Scan QR code button. Crash!

Device: iPhone8+, iOS 13.5.1

**Comment by SebastienGllmt** [comment]
Should  be fixed by https://github.com/Emurgo/yoroi-mobile/pull/850 and it will be part of Yoroi Mobile 2.2.3
Thanks for reporting the issue!
